### ISSUE TITLE
Exception while running SimpleExport.java

### ISSUE THREAD

**Issue by vgvish** [one2team/highcharts-serverside-export#13]
We are looking to export highcharts based charts on the server side. I have deployed the dependent jars on eclipse and I tried running the sample SimpleExport.java, I get the below exception. We are using highcharts 2.2.3. Let me know what is it I am missing?

org.apache.batik.bridge.BridgeException: null:-1
The attribute "y" of the element <rect> is invalid
    at org.apache.batik.bridge.SVGRectElementBridge.buildShape(SVGRectElementBridge.java:119)
    at org.apache.batik.bridge.SVGShapeElementBridge.createGraphicsNode(SVGShapeElementBridge.java:60)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:213)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
    at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
    at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:208)
    at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
    at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
    at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
    at org.one2team.highcharts.server.export.SVGStreamRenderer.render(SVGStreamRenderer.java:30)
    at org.one2team.highcharts.server.export.HighchartsExporter.render(HighchartsExporter.java:44)
    at org.one2team.highcharts.server.export.HighchartsExporter.export(HighchartsExporter.java:26)
    at examples.SimpleExport.main(SimpleExport.java:34)

**Comment by reiern70** [comment]
see

https://github.com/one2team/highcharts-serverside-export/pull/15

You can now use maven to install project and required libraries. See comment on PR. You ca to use

http://mvnrepository.com/artifact/rhino/js/1.7R2.

It would be nice also to upgrade this to newer versions of batik, rihno, and higcharts
