### ISSUE TITLE
what i missed

### ISSUE THREAD

**Issue by chro008** [one2team/highcharts-serverside-export#18]
if i change highcharts.js to lastest version,It will throw exception like that:

org.mozilla.javascript.EcmaError: TypeError: Cannot find function attachEvent in object [object HTMLDocument]. (highcharts.src.js#14361)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3654)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3632)
    at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3660)
    at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3679)
    at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3743)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2247)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2214)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:3143)
    at script(highcharts.src.js:14361)
    at script(highcharts.src.js:14380)
    at script(highcharts.src.js:13071)
    at script(highcharts.src.js:12983)
    at script(highcharts.src.js:12957)
    at script.renderSVGFromObject(svg-renderer-highcharts.js:23)
    at script.renderSVGFromJson(svg-renderer-highcharts.js:2)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2487)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
    at org.mozilla.javascript.Context$1.run(Context.java:504)
    at org.mozilla.javascript.Context.call(Context.java:515)
    at org.mozilla.javascript.Context.call(Context.java:502)
    at org.mozilla.javascript.ScriptableObject.callMethod(ScriptableObject.java:1906)

so what shold i do when use the new version of highchart and export js

**Comment by chro008** [comment]
what ever,i could not find the correct way to deal this problem

**Comment by chro008** [comment]
at last,i use phantomjs to done the work,addr:https://github.com/highcharts/highcharts-export-server/tree/master/phantomjs

**Comment by biggianteye** [comment]
This repo hasn't been touched in five years. I don't think you are going to get a response.

**Comment by chro008** [comment]
@biggianteye  although i also think so,but i stilled hoped i couldget more infomation from the author
